### PR TITLE
All-new UI

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by pylerSM** [comment]
If fine, I would expect Xposed repo release now.

**Comment by pylerSM** [comment]
@devadvance hmm?

**Comment by devadvance** [comment]
Sorry @pylerSM since there were conflicts I had to sit down on a PC and merge from CLI for once :stuck_out_tongue:

**Comment by pylerSM** [comment]
Yes it was caused by https://github.com/devadvance/rootcloak/pull/82#issuecomment-234819057 so just reverting was enough I think. sorry :D I didntt expect I would rework UI :D

**Review by goodtobebak2020 — APPROVED** [review]

**Pull request merged**
