### PR TITLE
Native hook improvements

### PR DESCRIPTION
**Pull request by NHellFire**
Added strcasestr and moved the checking to separate functions so we don't have to edit each one separately.

### CODE REVIEW

**Comment by pylerSM** [comment]
I think we should reimplement strcasecmp as our own void and and hook for it :)

**Comment by pylerSM** [comment]
I think popen should be checked too, if command starts with "su"

**Comment by pylerSM** [comment]
I think popen should be checked too, if command starts with "su"

**Comment by pylerSM** [comment]
Please test. I dont know but sometimes native hooking keeps failing. Files are OK but app does not start.

**Comment by NHellFire** [comment]
I've not had any issues on my Desire HD running CM13. I'm testing on that and x86_64 emulator.

**Comment by NHellFire** [comment]
I should also look at having open() check if we're opening /proc/PID/cmdline or /proc/PID/stat, then check if it's su so that we can hide it from ps.

**Comment by pylerSM** [comment]
Yes, it would be useful. Try it please if you know how to do it :)

**Comment by NHellFire** [comment]
Got that working now.
```
root@aceopt:/ # LD_PRELOAD=/data/local/tmp/librootcloak.so ps | grep daemonsu
1|root@aceopt:/ # ps | grep daemonsu
root      1672  1     2076   480   __skb_recv b6eba368 S daemonsu:mount:master
root      1728  1     6204   536   __skb_recv b6eba368 S daemonsu:master
```

**Comment by pylerSM** [comment]
Looks very well :)

**Pull request merged**
