### PR TITLE
Native hooking support

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by pylerSM** [comment]
Ready to be tested guys :D

**Comment by pylerSM** [comment]
Compiled RootCloak with this change.

[app-debug.zip](https://github.com/devadvance/rootcloak/files/367159/app-debug.zip)

**Comment by devadvance** [comment]
Should probably remove the native binaries from the repo. They should be built from source (for all target architectures) from source during release.

**Comment by devadvance** [comment]
*precompiled binaries

**Comment by pylerSM** [comment]
Removed. But I dont know how to build them automatically during APK build, :(

**Comment by pylerSM** [comment]
Finally ready to be merged.

**Comment by pylerSM** [comment]
I think it is fine @devadvance. Ready to be merged I think.

**Comment by devadvance** [comment]
I'm looking at how to automatically build the binaries as part of release. I'll merge this as a separate beta branch for testing, and add that on top once I have it set correctly.

**Comment by devadvance** [comment]
Merged into 3.0beta branch for further work.

**Comment by pylerSM** [comment]
Ok:)

**Comment by pylerSM** [comment]
"I'm looking at how to automatically build the binaries as part of release. I'll merge this as a separate beta branch for testing, and add that on top once I have it set correctly."

Actually, it was easy. https://github.com/devadvance/rootcloak/pull/72

**Comment by devadvance** [comment]
It looks like the best NDK gradle build support comes with either the 0.70-experimental plugin or the latest 2.2-alpha plugin.

0.70: https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html#0
2.2-alpha: https://sites.google.com/a/android.com/tools/tech-docs/external-c-builds

Is it worth switching to CMake?

**Comment by hikaritenchi** [comment]
In my projects to get things to build correctly, I use two modules. We currently have one, "app", but you can make a new Android Library module, say called "nativehooks":
app's build.gradle:
`compile project( ":nativehooks" )`
nativehooks's build.gradle:
`classpath 'com.android.tools.build:gradle-experimental:0.8.0-alpha1'`
I was using the 0.8.0-alpha1 plugin for various reasons, maybe 0.70 is better?

**Comment by pylerSM** [comment]
It is fully buildable so I am ok as it is. Release new version and then do what you wish with code  :)

**Pull request closed without merging**
