### PR TITLE
Auto build binaries during APK build

### PR DESCRIPTION
**Pull request by pylerSM**
WIP do not merge

### CODE REVIEW

**Comment by pylerSM** [comment]
It is fine now :) Works

**Comment by pylerSM** [comment]
Please configure NDK path for travis. @devadvance 


Btw, during gradle sync you maybe get "ExecutionException: Compiler exited with error code 1" but building works.. read this https://code.google.com/p/android/issues/detail?id=206500

**Comment by devadvance** [comment]
Can it be done via the ANDROID_NDK_HOME env variable instead of local.properties?

Either way, I think we can just borrow the before_install section from Google's sample: https://github.com/googlesamples/android-ndk/blob/master/.travis.yml

**Comment by pylerSM** [comment]
Probably ok, i am not familiar with travis :)

**Comment by pylerSM** [comment]
WTF, it should work but it didnt.

**Comment by pylerSM** [comment]
Finally fixed this BADBOY :D

**Comment by devadvance** [comment]
Awesome work! Merging now into 3.0beta :smile:

**Pull request merged**
